### ISSUE TITLE
A related work recommendation

### ISSUE THREAD

**Issue by yukang2017** [Vision-CAIR/LongVU#1]
Dear authors,

Thanks for your great work! The method of LongVU is promising and the results are very strong. 

Our work, LongVILA (https://www.arxiv.org/pdf/2408.10188), is a very related work in long video and language model understanding. It would be much appreciated if you could include this work for discussion in your revision. Thanks a lot!

Regards,
Yukang Chen

**Comment by xiaoqian-shen** [comment]
Hi Yukang,

We will update a version including this great work in next recent submission.

Xiaoqian

**Comment by yukang2017** [comment]
Great! Thanks.

**Comment by patrick-tssn** [comment]
@xiaoqian-shen Thank you for your excellent work. I would like to recommend two related studies that might interest you:

1. **PLLaVA (https://arxiv.org/abs/2404.16994)** - This paper explores the use of naive adaptive pooling techniques to enhance video understanding.

2. **VideoLLaMB (https://arxiv.org/abs/2409.01071)** - This work focuses on incorporating a recurrent memory mechanism to compress video history more effectively.

**Comment by mhelhoseiny** [comment]
Hi Yukang, thx for your email, appreciated! , would suggest that you also
consider citing earlier work on long video understanding including for
example goldfish paper at ECCV24 among others. Perhaps check the related
work section in the paper.
