### ISSUE TITLE
Temporal reduction strategy

### ISSUE THREAD

**Issue by aldo-f8** [Vision-CAIR/LongVU#13]
In the paper you mention that you apply a "temporal reduction strategy on the frame sequence by leveraging the prior knowledge from DINOv2". 
Am I wrong or this is not implemented in the code you released?

**Comment by xiaoqian-shen** [comment]
It is implemented in this function [here](https://github.com/Vision-CAIR/LongVU/blob/1ca42869fd456ecfef8acdc2aaa01e43864431e0/longvu/cambrian_arch.py#L839).
