### ISSUE TITLE
LongVU pretrained models for video features extraction

### ISSUE THREAD

**Issue by mustafahalimeh** [Vision-CAIR/LongVU#15]
Thank you for sharing this amazing work, we are interested in trying the extracted semantics of your trained models from videos related to action classification. However, we are not sure if this is possible (extracting temporal-spatial features) to be done on videos only dataset.
Would you please elaborate more about how it is done by an example.
Thank you

**Comment by xiaoqian-shen** [comment]
Hi, our model can extract video features frame by frame, perform token reduction on the video, and then concatenate the tokens as visual input for alignment with the LLM. The LLM is then used for captioning or VQA tasks. 

For action classification, one solution is to add a classification head to one of the LLM's special tokens for this downstream task. Alternatively, you could directly optimize the LLM to predict the action class name corresponding to the input video.
