### ISSUE TITLE
Finetuning from an image checkpoint does not work

### ISSUE THREAD

**Issue by geomlyd** [Vision-CAIR/LongVU#19]
Hello there, thanks for releasing your code! When I try to finetune one of the image-trained checkpoints (e.g. `LongVU_Llama3_2_3B_img`), [this line](https://github.com/Vision-CAIR/LongVU/blob/1ca42869fd456ecfef8acdc2aaa01e43864431e0/longvu/vision_sampler.py#L380C1-L380C78) fails, with the error being that the `VisionCrossAttentionLayer` has no attribute `pos_embed_0`. 

As far as I can understand, this error seems to be due to the fact that the pretrained config of this model has `image_token_len` 576, and this results in these layers only attending to a single key-value pair from the features of each vision tower. The arguments for finetuning include `--image_token_len 144`, but it seems to me that this takes no effect anywhere. Could there be some error in how these modules get instantiated, or am I not using something correctly?

**Comment by xiaoqian-shen** [comment]
As mentioned in README [here](https://github.com/Vision-CAIR/LongVU/blob/1ca42869fd456ecfef8acdc2aaa01e43864431e0/README.md?plain=1#L135). You need to change the config from 576 to 144 for video finetuning.

**Comment by xiaoqian-shen** [comment]
The argument has been used [here](https://github.com/Vision-CAIR/LongVU/blob/1ca42869fd456ecfef8acdc2aaa01e43864431e0/longvu/cambrian_arch.py#L63).
