### ISSUE TITLE
About training time cost

### ISSUE THREAD

**Issue by HenryHZY** [Vision-CAIR/LongVU#2]
@xiaoqian-shen Hi, thanks for your great project!

As mentioned in the paper, "Our model is trained on 64 NVIDIA H100 GPUs." 

Could you please share the training time cost? Thank you.

**Comment by xiaoqian-shen** [comment]
Thanks for asking this. For the 7B version, image training stage takes for 24h and video training stage takes for 28h.

**Comment by HenryHZY** [comment]
Thanks for the reply!
