### ISSUE TITLE
LongVU with Qwen2-0.5B has Zero Loss and NaN grad_norm

### ISSUE THREAD

**Issue by Amshaker** [Vision-CAIR/LongVU#27]
Hi @xiaoqian-shen ,

I am trying to run the codebase with Qwen/Qwen2-0.5B-Instruct instead of Qwen/Qwen2-7B-Instruct using 64 GPUs, but the loss is always zero, and grad_norm started with NaN:

<img width="612" alt="image" src="https://github.com/user-attachments/assets/cb46fbcd-ff24-4366-a6f4-e77090f26ca7">

I verified the transformer version of Qwen2-0.5B and tried to reduce the LR, but the problem still exists. 

The steps I did to run Qwen2-0.5B are: (1) I changed [the baseline checkpoint](https://github.com/Vision-CAIR/LongVU/blob/1ca42869fd456ecfef8acdc2aaa01e43864431e0/scripts/train_image_qwen.sh#L2C1-L2C16) from "Qwen/Qwen2-7B-Instruct" to "Qwen/Qwen2-0.5B-Instruc". (2) I modified your [configuration file](https://huggingface.co/Vision-CAIR/LongVU_Qwen2_7B/blob/main/config.json) to align it with Qwen2-0.5B instead of Qwen2-7B. Here is the new configuration for Qwen2-0.5B:
```
{ 
  "_name_or_path": "/tmp/iopath_cache/manifold_cache/tree/users/shenx/models/checkpoints/Cambrian_Qwen2_ov_query_drop",
  "architectures": [
    "CambrianQwenForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "connect_layer": 2,
  "connector_depth": 3,
  "connector_only": true,
  "dino_threshold": 0.83,
  "drop_threshold": 0.8,
  "eos_token_id": 151645,
  "frame_pos": false,
  "freeze_mm_mlp_adapter": false,
  "hidden_act": "silu",
  "hidden_size": 896,
  "highres": false,
  "highres_connect": false,
  "image_aspect_ratio": "pad",
  "image_position": 91,
  "image_token_len": 576,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "is_image_newline": true,
  "is_st_sampler": false,
  "lowres_token": 8,
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "mm_patch_merge_type": "flat",
  "mm_projector_lr": null,
  "mm_projector_type": "sva",
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_sampler_lr": null,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower_aux_list": [
    "siglip/CLIP-ViT-SO400M-14-384",
    "facebook/dinov2-giant-res378"
  ],
  "mm_vision_tower_aux_token_len_list": [
    576,
    576
  ],
  "mm_vision_tower_lr": null,
  "model_type": "cambrian_qwen",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "num_of_vision_sampler_layers": 10,
  "num_query_group": 1,
  "pretraining_tp": 1,
  "query_num_list": [
    576
  ],
    "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": null,
  "spmd_debug": null,
  "spmd_fsdp_sharding": null,
  "spmd_mesh": null,
  "start_of_vision_sampler_layers": 0,
  "stride_of_vision_sampler_layers": 3,
  "tie_word_embeddings": true,
  "tokenizer_model_max_length": 8192,
  "tokenizer_padding_side": "right",
  "torch_dtype": "float32",
  "transformers_version": "4.44.2",
  "tune_mm_mlp_adapter": false,
  "unfreeze_mm_vision_tower": false,
  "use_cache": false,
  "use_mm_proj": true,
  "use_pos_skipping": false,
  "use_sliding_window": false,
  "vision_hidden_size": 1024,
  "vision_tower_aux_token_len_list": [
    576,
    576
  ],
  "vocab_size": 151936
}

```

I kept the original configurations except those related to Qwen2-7B; I changed them to the original configuration of Qwen2-0.5B (i.e., hidden_size, num_attention_heads, intermediate_size, vocab_size, ...). 

Can you please let me know if there is anything else I have to do to run LongVU with Qwen2-0.5B?
Your help in this matter is highly appreciated.

Thank You,
Abdelrahman.

**Comment by zjukop** [comment]
Have you solved this problem? @Amshaker

**Comment by liuyang811** [comment]
> Have you solved this problem? @Amshaker

same problem
