### ISSUE TITLE
Question about the format of panda video dataset

### ISSUE THREAD

**Issue by Amshaker** [Vision-CAIR/LongVU#30]
Hi @xiaoqian-shen ,

I followed the [link you shared ](https://huggingface.co/datasets/shenxq/VideoChat2) to downlaod the raw video data. However, I am not able to download the videos you used from panda:

<img width="871" alt="image" src="https://github.com/user-attachments/assets/76566b9c-bb2b-48bb-afe0-77cbcd4b274d">

The link just contains .csv with the these attributes (videoID,url,timestamp,caption,matching_score):

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/396ad7a8-5c28-4ea7-8523-5cbd56e5258f">

Although I tried to download the original panda_2m dataset from the [here](https://huggingface.co/datasets/multimodalart/panda-70m), I am still not able to reach the required format you used in your training. Your format for the dataset is as follows: 

<img width="1395" alt="image" src="https://github.com/user-attachments/assets/20d29854-3c96-4e64-9d63-ad53deac3217">

Can you please upload the 27,092 .npy files you used in the training for panda dataset? Or at least please let me know how to reach from the training format from the original videos?

Your help is highly appreciated.

Best Regards,
Abdelrahman.

**Comment by xiaoqian-shen** [comment]
Hi, we download panda dataset from ShareGPT4Video using this [script](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/blob/main/user_download/download_panda_video.py) with [panda.csv](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/raw/main/user_download/panda.csv) and save as `.npy`.
Or you can also find the raw videos they provided in [here](https://huggingface.co/datasets/ShareGPT4Video/ShareGPT4Video/tree/main/zip_folder/panda).

**Comment by Amshaker** [comment]
Thanks for your reply, I will close this issue since the problem is solved.
