### ISSUE TITLE
Cambrian-Llama3_1-8b-t576 not found

### ISSUE THREAD

**Issue by joslefaure** [Vision-CAIR/LongVU#4]
In the `conversation.py`, there are some lines that read like this?
```
self.tokenizer = AutoTokenizer.from_pretrained(
          PathManager.get_local_path(
                        "manifold://xr_core_ai_asl_llm/tree/users/shenx/models/Cambrian-Llama3_1-8b-t576/"
            )
)
```
Where can I download the `Cambrian-Llama3_1-8b-t576` model? Thank you

**Comment by xiaoqian-shen** [comment]
Hi, thanks for raising this issue. Sorry we forgot to change this path to the external link. We already changed this [line](https://github.com/Vision-CAIR/LongVU/blob/dca2a91544090d3325e1556293d22a60eb895255/longvu/conversation.py#L133) to our pubic huggingface model. And the tokenizer should be the same across llama3.1 and llama3.2 models. Please let me know if it fixes the problem.

**Comment by joslefaure** [comment]
That fixes it. Thank you very much for your prompt assistance.
